### ISSUE TITLE
Add apns-collapse-id

### ISSUE THREAD

**Issue by v57** [kylebrowning/swift-nio-apns#14]
iOS 10 supports removable notifications by using `apns-collapse-id` header. That would be cool if you make this feature

https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html
> The appropriate encoding to employ for the `apns-id`, `apns-expiration`, and `apns-collapse-id` request headers differs depending on whether it is part of the initial or a subsequent POST operation, as follows:
The first time you send these headers, encode them with incremental indexing to allow the header names to be added to the dynamic table
Subsequent times you send these headers, encode them as literal header fields without indexing

**Comment by kylebrowning** [comment]
Seems appropriate and pretty easy to do. Ill submit a PR soon.

**Comment by kylebrowning** [comment]
Gives this a whirl @v57

**Comment by v57** [comment]
Thank you so much. Thats exactly what i need 🥳
