### ISSUE TITLE
retrieving the http/2 multiplexer 

### ISSUE THREAD

**Issue by weissi** [kylebrowning/swift-nio-apns#20]
In https://github.com/kylebrowning/swift-nio-apns/blob/master/Sources/NIOAPNS/APNSConnection.swift#L22-L40 I just saw that the way you retrieve the http2 multiplexer isn't 100% correct. The issue is that the `channelInitializer` for `ClientBootstrap`s might be invoked more than once. That is because of happy eyeballs (there might be two channels generated, one for IPv4 and one for IPv6).

In NIO 2.1.0 @Palleas [added](https://github.com/apple/swift-nio/pull/974) a new method that should make it quite straightforward to retrieve the multiplexer safely: [`ChannelPipeline.handler(type:)`](https://apple.github.io/swift-nio/docs/current/NIO/Classes/ChannelPipeline.html#/s:3NIO15ChannelPipelineC7handler4typeAA15EventLoopFutureCyxGxm_tAA0B7HandlerRzlF).

The basic idea is:

```swift
let channelAndMultiplexer: EventLoopFuture<(Channel, HTTP2StreamMultiplexer )> = ClientBootstrap(...)
    .channelInitializer { ... }
    ....
    .connect()
    .flatMap { channel in
        channel.pipeline.handler(type: HTTP2StreamMultiplexer.self).map { multiplexer in (channel, multiplexer) }
    }
```

This will actually work because `connect` only returns you one channel. From that one `Channel` you can then get the `HTTP2StreamMultiplexer` with the new `handler(type:)` in `ChannelPipeline`.

More info:
- https://github.com/apple/swift-nio/issues/966
- https://github.com/apple/swift-nio/pull/974
- https://github.com/grpc/grpc-swift/issues/438 (<-- grpc-swift actually had a bug because of this)

**Comment by kylebrowning** [comment]
@weissi 

So something like this?
```swift
    public static func connect(configuration: APNSConfiguration, on eventLoop: EventLoop) -> EventLoopFuture<APNSConnection> {
        let bootstrap = ClientBootstrap(group: eventLoop)
            .channelOption(ChannelOptions.socket(IPPROTO_TCP, TCP_NODELAY), value: 1)
            .channelInitializer { channel in
                do {
                    let sslContext = try NIOSSLContext(configuration: configuration.tlsConfiguration)
                    let sslHandler = try NIOSSLClientHandler(context: sslContext, serverHostname: configuration.url.host)
                    return channel.pipeline.addHandler(sslHandler).flatMap {
                        channel.configureHTTP2Pipeline(mode: .client) { _, _ in
                            fatalError("server push not supported")
                        }.map { _ in }
                    }
                } catch {
                    channel.close(mode: .all, promise: nil)
                    return channel.eventLoop.makeFailedFuture(error)
                }
            }

        return bootstrap.connect(host: configuration.url.host!, port: 443).flatMap { channel in
            channel.pipeline.context(handlerType: HTTP2StreamMultiplexer.self).map { context in
                context.handler as! HTTP2StreamMultiplexer
            }.map { multiplexer in
                return APNSConnection(channel: channel, multiplexer: multiplexer, configuration: configuration)
            }
        }
    }
```

**Comment by weissi** [comment]
Perfect, thanks for the quick fix!
